"""Generate GitHub-safe navigation from the same snapshot as the SVG panels."""
from common import DATA, ROOT, read_json, run
from fetch_builds import safe_url
from render_build_spotlight import sync_label
from svg import esc, shorten


def link(url, label):
    url = safe_url(url)
    return f'<a href="{esc(url)}">{esc(label)}</a>' if url else esc(label)


def image(name, alt, width=860, url=""):
    markup = f'<img src="./{name}.svg" width="{width}" alt="{esc(alt)}">'
    return f'<a href="{esc(safe_url(url))}">{markup}</a>' if safe_url(url) else markup


def render(data, stream):
    projects = data["projects"]
    project = projects[0] if projects else None
    parts = ['<!-- Generated by scripts/render_readme.py. Edit the generator, not this snapshot. -->', '<div align="center">',
             '<h3>filan214@github:~$ git contributions --calendar</h3>',
             image("contrib-heatmap", "GitHub contribution calendar with streaks, peak day, and monthly totals", url="https://github.com/filan214?tab=overview"), '<br>',
             image("commit-log", "The featured repository's actual default-branch tip commit", url=project["commit"]["url"] if project else ""), '<br>',
             '<h3>filan214@github:~$ neofetch --github</h3>',
             '<table align="center" width="860" cellpadding="0" cellspacing="0"><tr>',
             '<td width="43%" align="center">' + image("filan-ascii", "Animated ASCII portrait of Filan from the supplied photograph", 370) + '</td>',
             '<td width="57%" align="center">' + image("info-card", "GitHub profile, real repository counts, latest project, and code languages", 490, "https://github.com/filan214?tab=repositories") + '</td>',
             '</tr></table>', '<br>', '<h3>filan214@github:~$ git portfolio --latest</h3>',
             image("recent-build", "Recent Build Spotlight: " + (project["title"] + ", measured commit activity and language bytes. Open the repository." if project else "No eligible public projects."), url=project["url"] if project else "")]
    if project:
        actions = [link(project["url"], "↗ Explore code"), link(project["commit"]["url"], "↗ Latest commit"), link(project["url"] + "/commits", "↗ Commit history")]
        if safe_url(project["homepage"]):
            actions.append(link(project["homepage"], "↗ Open project site"))
        parts.append('<p>' + ' &nbsp; · &nbsp; '.join(actions) + '</p>')
    parts += ['<h3>filan214@github:~$ ps --repos</h3>',
              '<table width="860"><tr><th width="27%" align="left">Repository</th><th width="15%" align="left">Code</th><th width="25%" align="left">Commits · 28d</th><th width="19%" align="left">Last push (UTC)</th><th width="14%" align="left">Explore</th></tr>']
    for index, other in enumerate(projects):
        actions = [link(other["commit"]["url"], "Commit")]
        if safe_url(other["homepage"]):
            actions.append(link(other["homepage"], "Site"))
        spark = image(f"repo-activity-{index+1}", other["name"] + ": daily default-branch commits over 28 days, all authors; line scaled to its own peak", 180, other["url"] + '/commits')
        parts.append('<tr><td>' + link(other["url"], other["name"]) + '</td><td>' + esc(other["language"] or "Unreported") + '</td><td>' + spark + '</td><td>' + esc(other["pushed_at"][:10]) + '</td><td>' + ' · '.join(actions) + '</td></tr>')
    if not projects:
        parts.append('<tr><td colspan="5">No eligible public projects.</td></tr>')
    parts += ['</table>', '<p>28-day default-branch activity · all authors · each line scaled to its own peak</p>', '<br>',
              image("commit-stream", "Scrolling cross-repository feed of up to ten actual public pushes, one exact head commit per push; full linked log below"),
              '<details>', f'<summary>Read all {len(stream["pushes"])} pushes &amp; open commits</summary>', '<br>',
              '<table width="860"><tr><th align="left" width="20%">Pushed (UTC)</th><th align="left" width="25%">Repository / branch</th><th align="left" width="55%">Head commit</th></tr>']
    for item in stream["pushes"]:
        repo_url = 'https://github.com/' + item['repo']
        parts.append('<tr><td>' + esc(item['created_at'].replace('T', ' ').removesuffix('Z')) + '</td><td>'
                     + link(repo_url, item['repo']) + '<br>' + esc(item['branch']) + '</td><td>'
                     + link(item['url'], item['sha'][:7]) + ' ' + esc(item['message']) + '</td></tr>')
    if not stream["pushes"]:
        parts.append('<tr><td colspan="3">No eligible public pushes in GitHub’s available event window.</td></tr>')
    parts += ['</table>', '<p>Public push events by filan214 across repositories and branches. GitHub exposes a limited event window and may delay events; fewer than ten results are shown when that is all it supplies. Profile automation and configured exclusions are omitted.</p>',
              '<p>Push feed synced: ' + esc(sync_label(stream)) + ' · ' + link('https://github.com/filan214/filan214/blob/main/data/commit-stream.json', 'Inspect source snapshot') + '</p>', '</details>', '<br>',
              '<h3>filan214@github:~$ languages --bytes</h3>',
              image("languages", "Actual language bytes across eligible public projects; code proportions, not proficiency", url="https://github.com/filan214?tab=repositories"), '<br>',
              image("tagline", "Rotating facts derived from the current GitHub profile and project snapshot"), '<br>',
              '<details><summary>Data sources &amp; freshness</summary>',
              '<p>Last successful sync: <strong>' + esc(sync_label(data)) + '</strong>. Scheduled hourly, with manual refresh available. GitHub schedules, contribution processing, and image caches can delay updates.</p>',
              '<p>Project selection and languages exclude this profile repository, configured exclusions, forks, and archives. The contribution calendar and account counts reflect the full public GitHub profile, including automation. Commit dates describe repository history; they do not prove a release or personal completion.</p>',
              '<p>The photograph is supplied by Filan. All displayed activity and code statistics come from GitHub. Failed refreshes leave the previous successful snapshot and its timestamp visible.</p>',
              '<p>' + link("https://github.com/filan214/filan214/actions/workflows/update-profile-art.yml", "Refresh workflow") + ' · ' + link("https://github.com/filan214/filan214/blob/main/data/builds.json", "Project snapshot") + ' · ' + link("https://github.com/filan214/filan214/blob/main/data/contributions.json", "Contribution data") + ' · ' + link("https://github.com/filan214/filan214/blob/main/data/languages.json", "Language data") + '</p>',
              '</details>', '</div>']
    return '\n\n'.join(parts) + '\n'


if __name__ == "__main__":
    run(lambda: (ROOT / "README.md").write_text(render(read_json(DATA / "builds.json"), read_json(DATA / "commit-stream.json")), encoding="utf-8", newline="\n"))
