"""Generate GitHub-safe navigation from the same snapshot as the SVG panels."""
from common import DATA, ROOT, read_json, run
from fetch_builds import safe_url
from fetch_highlights import FINANCE_APP
from render_build_spotlight import sync_label
from svg import esc, shorten


def link(url, label):
    url = safe_url(url)
    return f'<a href="{esc(url)}">{esc(label)}</a>' if url else esc(label)


def image(name, alt, width=860, url=""):
    markup = f'<img src="./{name}.svg" width="{width}" alt="{esc(alt)}">'
    return f'<a href="{esc(safe_url(url))}">{markup}</a>' if safe_url(url) else markup


def render(data, stream, highlights=None):
    projects = data["projects"]
    project = projects[0] if projects else None
    parts = ['<!-- Generated by scripts/render_readme.py. Edit the generator, not this snapshot. -->', '<div align="center">',
             '<h3>filan214@github:~$ git contributions --calendar</h3>',
             image("contrib-heatmap", "GitHub contribution calendar with streaks, peak day, and monthly totals", url="https://github.com/filan214?tab=overview"), '<br>',
             image("commit-log", "The featured repository's actual default-branch tip commit", url=project["commit"]["url"] if project else ""), '<br>',
             '<h3>filan214@github:~$ neofetch --github</h3>',
             '<table align="center" width="860" cellpadding="0" cellspacing="0"><tr>',
             '<td width="43%" align="center">' + image("filan-ascii", "Animated ASCII portrait of Filan from the supplied photograph", 370) + '</td>',
             '<td width="57%" align="center">' + image("info-card", "GitHub profile, real repository counts, latest project, and code languages", 490, "https://github.com/filan214?tab=repositories") + '</td>',
             '</tr></table>', '<br>', '<h3>filan214@github:~$ git portfolio --latest</h3>',
             image("recent-build", "Recent Build Spotlight: " + (project["title"] + ", measured commit activity and language bytes. Open the repository." if project else "No eligible public projects."), url=project["url"] if project else "")]
    if project:
        actions = [link(project["url"], "↗ Explore code"), link(project["commit"]["url"], "↗ Latest commit"), link(project["url"] + "/commits", "↗ Commit history")]
        if safe_url(project["homepage"]):
            actions.append(link(project["homepage"], "↗ Open project site"))
        parts.append('<p>' + ' &nbsp; · &nbsp; '.join(actions) + '</p>')
    parts += ['<h3>filan214@github:~$ ps --repos</h3>',
              '<table width="860"><tr><th width="27%" align="left">Repository</th><th width="15%" align="left">Code</th><th width="25%" align="left">Commits · 28d</th><th width="19%" align="left">Last push (UTC)</th><th width="14%" align="left">Explore</th></tr>']
    for index, other in enumerate(projects):
        actions = [link(other["commit"]["url"], "Commit")]
        if safe_url(other["homepage"]):
            actions.append(link(other["homepage"], "Site"))
        spark = image(f"repo-activity-{index+1}", other["name"] + ": daily default-branch commits over 28 days, all authors; line scaled to its own peak", 180, other["url"] + '/commits')
        parts.append('<tr><td>' + link(other["url"], other["name"]) + '</td><td>' + esc(other["language"] or "Unreported") + '</td><td>' + spark + '</td><td>' + esc(other["pushed_at"][:10]) + '</td><td>' + ' · '.join(actions) + '</td></tr>')
    if not projects:
        parts.append('<tr><td colspan="5">No eligible public projects.</td></tr>')
    parts += ['</table>', '<p>28-day default-branch activity · all authors · each line scaled to its own peak</p>', '<br>',
              image("commit-stream", "Scrolling cross-repository feed of up to ten actual public pushes, one exact head commit per push; full linked log below"),
              '<details>', f'<summary>Read all {len(stream["pushes"])} pushes &amp; open commits</summary>', '<br>',
              '<table width="860"><tr><th align="left" width="20%">Pushed (UTC)</th><th align="left" width="25%">Repository / branch</th><th align="left" width="55%">Head commit</th></tr>']
    for item in stream["pushes"]:
        repo_url = 'https://github.com/' + item['repo']
        parts.append('<tr><td>' + esc(item['created_at'].replace('T', ' ').removesuffix('Z')) + '</td><td>'
                     + link(repo_url, item['repo']) + '<br>' + esc(item['branch']) + '</td><td>'
                     + link(item['url'], item['sha'][:7]) + ' ' + esc(item['message']) + '</td></tr>')
    if not stream["pushes"]:
        parts.append('<tr><td colspan="3">No eligible public pushes in GitHub’s available event window.</td></tr>')
    parts += ['</table>', '<p>Public push events by filan214 across repositories and branches. GitHub exposes a limited event window and may delay events; fewer than ten results are shown when that is all it supplies. Profile automation and configured exclusions are omitted.</p>',
              '<p>Push feed synced: ' + esc(sync_label(stream)) + ' · ' + link('https://github.com/filan214/filan214/blob/main/data/commit-stream.json', 'Inspect source snapshot') + '</p>', '</details>', '<br>',
              '<h3>filan214@github:~$ languages --bytes</h3>',
              image("languages", "Actual language bytes across eligible public projects; code proportions, not proficiency", url="https://github.com/filan214?tab=repositories"), '<br>',
              image("tagline", "Rotating facts derived from the current GitHub profile and project snapshot"), '<br>']
    if highlights:
        parts += showcase_sections(highlights)
    parts += ['<h3>filan214@github:~$ sources --inspect · Data sources &amp; freshness</h3>']
    if highlights:
        parts.append(image("data-freshness", "Recorded sync times for projects, public push events, and project spotlights, with calendar and language snapshot dates", url="https://github.com/filan214/filan214/actions/workflows/update-profile-art.yml"))
    parts += ['<p>Refreshed hourly at minute 17 · also on profile pushes and manual runs</p>',
              '<details><summary>Inspect sources, measurement scope &amp; refresh behavior</summary>', '<br>',
              '<table width="860"><tr><th align="left">Snapshot</th><th align="left">What it measures</th></tr>']
    for name, label, detail in [
        ("builds", "Projects & activity", "Public repository metadata and 28-day default-branch commit history, all authors. Synced " + sync_label(data) + "."),
        ("commit-stream", "Cross-repo pushes", "Available public push events by filan214; one exact head commit per push. Synced " + sync_label(stream) + "."),
        ("highlights", "Finance & EPL spotlights", "File inventories pinned to the displayed source commit, 90-day commit history, latest public workflow observation, and a public finance landing-page check."),
        ("contributions", "Contribution calendar", "GitHub contribution HTML: full account totals, including automation."),
        ("languages", "Language mix", "GitHub Linguist byte counts from eligible public repositories. Code proportions, not proficiency.")]:
        parts.append('<tr><td>' + link("https://github.com/filan214/filan214/blob/main/data/" + name + ".json", label) + '</td><td>' + esc(detail) + '</td></tr>')
    parts += ['</table>',
              '<p>Project selection and aggregate languages exclude this profile repository, configured exclusions, forks, and archives. The two curated spotlights follow AIFinanceTracker and epl-season-forecast while they remain public and active.</p>',
              '<p>Source counts show files and registered tools, not passed tests or feature-health checks. Workflow results identify their commit. The EPL card visualizes source structure and commit history. The finance app check only tests its public landing page, without accessing an account or financial data.</p>',
              '<p>GitHub schedules, event delivery, source analysis, and image caches can delay updates. A failed refresh keeps the last published snapshot and its recorded timestamps. The portrait is supplied by Filan.</p>',
              '<p>' + link("https://github.com/filan214/filan214/actions/workflows/update-profile-art.yml", "↗ Refresh workflow") + ' &nbsp; · &nbsp; ' + link("https://github.com/filan214/filan214/tree/main/scripts", "↗ Explore the generators") + '</p>',
              '</details>', '</div>']
    return '\n\n'.join(parts) + '\n'


def showcase_sections(data):
    finance, epl = data["projects"]["finance"], data["projects"]["epl"]
    parts = ['<h3>filan214@github:~$ showcase --finance · AI for everyday money</h3>',
             image("finance-spotlight", "Smart Finn Track: AI finance features observed in source, app page and tool counts, 90-day commit activity, and public landing-page availability", url=FINANCE_APP),
             '<p><strong>Smart Finn Track</strong> brings an AI advisor, spending insights, and monthly reports into a personal finance app.<br>Explore the product, then follow the code behind it.</p>',
             '<p>' + ' &nbsp; · &nbsp; '.join([link(FINANCE_APP, "↗ Open app"), link(finance["url"], "↗ Explore AIFinanceTracker"), link(finance["commit"]["url"], "↗ Latest source commit")]) + '</p>', '<br>',
             '<h3>filan214@github:~$ showcase --football · Sports Analytics &amp; Forecasting</h3>',
             image("epl-spotlight", "EPL Season Forecast: observed data-to-model pipeline, season data and test-file counts, development status, and actual 90-day commit history", url=epl["url"]),
             '<p><strong>One match is uncertain. A season is a range of possibilities.</strong><br>EPL Season Forecast explores that range through Bayesian goal modeling, XGBoost outcomes, and season simulations.</p>',
             '<p>' + ' &nbsp; · &nbsp; '.join([link(epl["url"], "↗ Explore EPL project"), link(epl["url"] + "/tree/" + epl["commit"]["sha"] + "/pipeline/src/eplforecast", "↗ Inspect model pipeline"), link(epl["commit"]["url"], "↗ Latest source commit")]) + '</p>',
             '<details><summary>Follow the wider football analytics thread</summary>',
             '<p>' + link(epl["url"], "EPL season forecasting") + ' → ' + link("https://github.com/filan214/WC-prediction", "World Cup final modeling") + ' → ' + link("https://github.com/filan214/FormWAtch-Football", "Player-form analysis") + '</p>',
             '<p>Across league seasons, a World Cup final, and player form, I use the same predictive-modeling mindset: measure uncertainty, separate signal from noise, and make results understandable.</p>',
             '</details>', '<br>']
    return parts


if __name__ == "__main__":
    run(lambda: (ROOT / "README.md").write_text(render(read_json(DATA / "builds.json"), read_json(DATA / "commit-stream.json"), read_json(DATA / "highlights.json")), encoding="utf-8", newline="\n"))
